name: Build Image

on:
  release:
    types: [published]
  push:

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: chukysoria/workflows/.github/workflows/build-image.yml@53225111ea45f3f77a3010c09b2f27dbce3c5ae7
    with:
      tag-external-version: true
