name: Build Image

on:
  release:
    types: [published]
  push:

env:
  VERSION: 3.18
  GH_USER: chukysoria
  GH_REPO: docker-baseimage-alpine
  IMAGE_NAME: baseimage-alpine
  ARCH: arm32v7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
             ghcr.io/${{ env.GH_USER }}/${{ env.IMAGE_NAME }}            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.ref_name }}
            type=raw,value=${{ env.VERSION }}
            type=ref,event=branch,prefix=${{ env.VERSION }}-
            type=ref,event=tag,prefix=${{ env.VERSION }}-
            type=raw,value=latest,enable={{is_default_branch}},prefix=${{ env.ARCH }}-
            type=raw,value=${{ github.ref_name }},prefix=${{ env.ARCH }}-
            type=raw,value=${{ env.VERSION }},prefix=${{ env.ARCH }}-
            type=ref,event=branch,prefix=${{ env.ARCH }}-${{ env.VERSION }}-
            type=ref,event=tag,prefix=${{ env.ARCH }}-${{ env.VERSION }}-
          labels: |
            org.opencontainers.image.created=${{ env.NOW }}
            org.opencontainers.image.authors=Carlos Sanchez
            org.opencontainers.image.url=https://github.com/${{ env.GH_USER }}/${{ env.GH_REPO }}/packages
            org.opencontainers.image.documentation=https://docs.linuxserver.io/images/docker-baseimage-alpine
            org.opencontainers.image.source=https://github.com/${{ env.GH_USER }}/${{ env.GH_REPO }}
            org.opencontainers.image.version=${{ github.ref_name }}-ls
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.vendor=Carlos Sanchez
            org.opencontainers.image.licenses=GPL-3.0-only
            org.opencontainers.image.ref.name=${{ github.sha }}
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=baseimage-alpine image by Chukysoria    

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm/v7
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
          build-args: |
            BUILD_DATE=${{ env.NOW }}
