name: 'Release Drafter'

on:
  push:
    branches:
      - main
      - master
      - jammy
      - noble

jobs:
  update_release_draft:
    name: Release
    uses: chukysoria/workflows/.github/workflows/new-release.yml@v1.0.40
    with:
      tag-external-version: true
